<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="..\PalConfig.cs" Link="PalConfig.cs" />
    <Compile Include="..\Contracts.cs" Link="Contracts.cs" />
    <Compile Include="..\ConnectionManager.cs" Link="ConnectionManager.cs" />
    <Compile Include="..\PalworldService.cs" Link="PalworldService.cs" />
  </ItemGroup>
</Project>
